# Generated by Django 3.2.3 on 2021-07-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='image_url',
            new_name='image',
        ),
    ]
