# Generated by Django 3.2.3 on 2021-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_image_url_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='images/pets'),
        ),
    ]
