# Generated by Django 3.2.4 on 2021-06-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expenses',
        ),
    ]
