# Generated by Django 3.2.4 on 2021-06-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20210610_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookModel',
        ),
    ]
